# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "03:00"
      timezone: Europe/London
    groups:
      npm:
        patterns:
          - "*"
    open-pull-requests-limit: 10
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "03:00"
      timezone: Europe/London
    groups:
      npm:
        patterns:
          - "*"
    open-pull-requests-limit: 10
