version: "3.4"

services:
  laa-crime-forms-end-to-end-tests:
    volumes:
      - .:/e2e
    stdin_open: true # docker run -i
    tty: true # docker run -t
  nscc-provider:
    build: https://github.com/ministryofjustice/laa-submit-crime-forms.git#main
  nscc-caseworker:
    build: https://github.com/ministryofjustice/laa-assess-crime-forms.git#main
  nscc-appstore:
    build: https://github.com/ministryofjustice/laa-crime-application-store.git#main
