# This Docker Compose file defines two services: start_applications and nsm-e2e-tests.
# The start_applications service uses the jwilder/dockerize image and waits for a
# TCP connection to nsm-crm7-claim on port 3000 to be available.
# The nsm-e2e-tests service builds an image using the Dockerfile in the current directory,
# sets some environment variables, and mounts two volumes.

version: "3.9"
services:
  start_applications:
    image: jwilder/dockerize
    command: >
      -wait tcp://nsm-crm7-claim:3000
      -wait-retry-interval 10s
      -timeout 180s
    depends_on:
      - nsm-crm7-claim

  nsm-e2e-tests:
    build: .
    container_name: nsm-e2e-tests
    environment:
      - NSM_ASSESS_DEV_URL=https://nsmassessdev.apps.live.cloud-platform.service.justice.gov.uk/
      - NSM_CLAIMS_DEV_URL=https://crm7dev.apps.live.cloud-platform.service.justice.gov.uk/
    volumes:
      - .:/behave_local
      - ./data:/data

  nsm-crm7-claim:
    image: ${LAA_CLAIM_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/ministryofjustice/laa-claim-non-standard-magistrate-fee-dev-ecr:5996442cc161d38bf8289d14451856624f1e1605}
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY_BASE=needed_for_assets_precompile
      - RAILS_ENV=production
      - ENV=production
    command: ["./run.sh"]
