version: "3.4"

services:
  nsm-e2e-tests:
    volumes:
      - .:/e2e
    stdin_open: true # docker run -i
    tty: true # docker run -t
  nsm-crm7-claim:
    build: https://github.com/ministryofjustice/laa-claim-non-standard-magistrate-fee-backend.git#main
  nsm-crm7-assess:
    build: https://github.com/ministryofjustice/laa-assess-non-standard-magistrate-fee.git#main
