# This Docker Compose file sets up multiple services for a web application stack.
# The services include a database service (nsm-db-services), two application services (nsm-crm7-claim, nsm-crm7-assess), and an application store service (nsm-crm7-appstore).
# Each service is assigned a static IP address on the 'app_net' network, which is defined with a subnet of 172.20.0.0/16.
# The 'start_applications' service uses the 'dockerize' tool to wait for the other services to be available before starting.
# The 'laa-crime-forms-end-to-end-tests' service runs end-to-end tests for the application.
# Environment variables are used to configure the services, and volumes are used for data persistence and sharing files between the host and containers.
# This configuration allows for a full-stack application to be run and tested in an isolated environment with consistent IP addresses for inter-service communication.

version: "3.9"
networks:
  app_net:
    ipam:
      config:
        - subnet: 172.20.0.0/16
services:
  start_applications:
    container_name: start_applications
    image: jwilder/dockerize
    command: >
      -wait tcp://nsm-db-services:5432
      -wait tcp://nsm-crm7-claim:3000
      -wait tcp://nsm-crm7-assess:3000
      -wait tcp://nsm-crm7-appstore:8000
      -wait-retry-interval 10s
      -timeout 180s
    depends_on:
      - nsm-db-services
      - nsm-crm7-claim
      - nsm-crm7-assess
      - nsm-crm7-appstore

  laa-crime-forms-end-to-end-tests:
    container_name: laa-crime-forms-end-to-end-tests
    build: .
    environment:
      - NSM_ASSESS_DEV_URL=${NSM_ASSESS_DEV_URL}
      - NSM_CLAIMS_DEV_URL=${NSM_CLAIMS_DEV_URL}
    volumes:
      - .:/e2e
      - ./data:/data
    depends_on:
      - nsm-db-services
      - nsm-crm7-assess
    networks:
      - app_net

  # NSM Database services

  nsm-db-services:
    container_name: nsm-db-services
    image: postgres:bullseye
    volumes:
      - ./tmp/pgdata:/var/lib/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      app_net:
        ipv4_address: 172.20.1.10

  # NSM Claim service

  nsm-crm7-claim:
    container_name: nsm-crm7-claim
    image: ${LAA_CLAIM_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/ministryofjustice/laa-claim-non-standard-magistrate-fee-dev-ecr:5996442cc161d38bf8289d14451856624f1e1605}
    ports:
      - 3001:3000
    environment:
      - SECRET_KEY_BASE=needed_for_assets_precompile
      - RAILS_ENV=development
      - ENV=development
      - APP_STORE_URL=http://nsm-crm7-appstore:8000
      - SIDEKIQ_WEB_UI_USERNAME=sidekiq
      - SIDEKIQ_WEB_UI_PASSWORD=sidekiq
      - DATABASE_URL=postgresql://postgres:postgres@nsm-db-services:5432/laa-claim-non-standard-magistrate-fee-dev
      - LAA_PORTAL_IDP_METADATA_FILE=config/laa_portal/metadata/samlmock.xml
      - OMNIAUTH_TEST_MODE=true
    depends_on:
      - nsm-db-services
    command: |
      bin/rails db:prepare
    networks:
      app_net:
        ipv4_address: 172.20.1.1

  # NSM Assess service

  nsm-crm7-assess:
    container_name: nsm-crm7-assess
    image: ${LAA_CLAIM_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/crm7team/laa-assess-non-standard-magistrate-fee-dev:latest}
    ports:
      - 3002:3000
    environment:
      - SECRET_KEY_BASE=needed_for_assets_precompile
      - RAILS_ENV=development
      - ENV=development
      - SIDEKIQ_WEB_UI_USERNAME=sidekiq
      - SIDEKIQ_WEB_UI_PASSWORD=sidekiq
      - DATABASE_URL=postgresql://postgres:postgres@nsm-db-services:5432/laa_assess_non_standard_magistrate_fee_dev
      - OMNIAUTH_TEST_MODE=true
      - OMNIAUTH_AZURE_CLIENT_ID=''
      - OMNIAUTH_AZURE_CLIENT_SECRET=''
      - OMNIAUTH_AZURE_REDIRECT_URI=''
      - OMNIAUTH_AZURE_TENANT_ID=''
      - APP_STORE_URL=http://nsm-crm7-appstore:8000
      - APP_STORE_CLIENT_ID=
      - APP_STORE_TENANT_ID=
      - APP_STORE_CLIENT_SECRET=
      - DEV_AUTH_ENABLED=true
    depends_on:
      - nsm-db-services
    command: |
      bin/rails db:prepare
    networks:
      app_net:
        ipv4_address: 172.20.1.2

  # NSM Application Store service

  nsm-crm7-appstore:
    container_name: nsm-crm7-appstore
    image: ${LAA_CLAIM_IMAGE:-754256621582.dkr.ecr.eu-west-2.amazonaws.com/crm7team/laa-crime-application-store-dev:1ce881606ef4bc3d9198962ff6eec73efc760e34}
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOSTNAME=localhost
      - POSTGRES_NAME=laa_crime_application_store
      - DATABASE_URL=postgresql://postgres:postgres@nsm-db-services:5432/laa_crime_application_store
    depends_on:
      - nsm-db-services
    ports:
      - 8000:8000
    networks:
      app_net:
        ipv4_address: 172.20.1.3
