version: 2.1

# ------------------
# ORBS
# ------------------
orbs:
  aws-cli: circleci/aws-cli@4.1.3
  aws-ecr: circleci/aws-ecr@9.0.4
  orb-tools: circleci/orb-tools@10.1.0

# ------------------
# JOBS
# ------------------
jobs:
  run-e2e-tests:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - setup_remote_docker

      - aws-cli/setup:
          role_arn: $PROVIDER_ECR_ROLE_TO_ASSUME # this will use the env var
          region: $ECR_REGION
      - run:
          name: Pull NSCC provider image
          command: |
            ./.circleci/pull_image nscc-provider

      - aws-cli/setup:
          role_arn: $APPSTORE_ECR_ROLE_TO_ASSUME
          region: $ECR_REGION
      - run:
          name: Pull NSCC appstore image
          command: |
            ./.circleci/pull_image nscc-appstore

      - aws-cli/setup:
          role_arn: $CASEWORKER_ECR_ROLE_TO_ASSUME
          region: $ECR_REGION
      - run:
          name: Pull NSCC caseworker image
          command: |
            ./.circleci/pull_image nscc-caseworker

      - run:
          name: Build and check/wait for services to be up
          command: |
            docker-compose build
            docker-compose run start_applications
      - run:
          name: "Failure: output container logs to console"
          command: |
            docker-compose logs
          when: on_fail
      - run:
          name: Run end to end tests
          command: |
            docker-compose run laa-crime-forms-end-to-end-tests

# ------------------
# WORKFLOWS
# ------------------
workflows:
  test:
    jobs:
      - run-e2e-tests:
          context: nsm-e2e-test-production

  publish-orb:
    jobs:
      - hold_dev_orb_publishing:
          type: approval

      # orb-tools@10.1.0 compatible only
      - orb-tools/publish-dev:
          name: publish_dev_orb
          attach-workspace: false
          checkout: true
          orb-name: ministryofjustice/crime-forms-end-to-end-tests
          orb-path: orb.yml
          requires: 
            - hold_dev_orb_publishing
          context:
            - laa-crime-forms-orb-publishing

      - hold_production_orb_publishing:
          type: approval
          requires:
            - publish_dev_orb
          filters:
            branches:
              only:
                - main

      # orb-tools@10.1.0 compatible only
      - orb-tools/increment:
          name: publish_production_orb
          segment: patch
          orb-ref: ministryofjustice/crime-forms-end-to-end-tests
          orb-path: orb.yml
          requires:
            - hold_production_orb_publishing
          context:
            - laa-crime-forms-orb-publishing
          filters:
            branches:
              only:
                - main
