version: 2.1

# ------------------
# ORBS
# ------------------
orbs:
  aws-cli: circleci/aws-cli@4.1.2
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  run-e2e-tests:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout
      - setup_remote_docker

      - aws-cli/setup:
          role_arn: $PROVIDER_ECR_ROLE_TO_ASSUME # this will use the env var
          region: $ECR_REGION
      - run:
          name: Pull NSCC provider image
          command: |
            echo "Pulling NSCC provider image"
            ./.circleci/pull_image nscc-provider

      - aws-cli/setup:
          role_arn: $APPSTORE_ECR_ROLE_TO_ASSUME
          region: $ECR_REGION
      - run:
          name: Pull NSCC appstore image
          command: |
            echo "Pulling NSCC-appstore image"
            ./.circleci/pull_image nscc-appstore

      - aws-cli/setup:
          role_arn: $CASEWORKER_ECR_ROLE_TO_ASSUME
          region: $ECR_REGION
      - run:
          name: Pull NSCC caseworker image
          command: |
            echo "Pulling NSCC caseworker image"
            ./.circleci/pull_image nscc-caseworker

      - run:
          name: Build and check/wait for services to be up
          command: |
            docker-compose build
            docker-compose run start_applications
      - run:
          name: "Failure: output container logs to console"
          command: |
            docker-compose logs
          when: on_fail
      - run:
          name: Run end to end tests
          command: |
            docker-compose run laa-crime-forms-end-to-end-tests

workflows:
  build:
    jobs:
      - run-e2e-tests:
          context: nsm-e2e-test-production
