version: 2.1

# ------------------
# ORBS
# ------------------
orbs:
  aws-cli: circleci/aws-cli@4.0.0

jobs:
  run-e2e-tests:
    docker:
      - image: cimg/node:21.6.1
    steps:
      - checkout

      # Pull nsm claim image
      - aws-cli/setup:
          role_arn: $ECR_ROLE_TO_ASSUME # this will use the env var
          region: $ECR_REGION
      # - run:
      #     name: Install Docker Compose
      #     environment:
      #       COMPOSE_VERSION: "1.29.2"
      #     command: |
      #       curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
      #       chmod +x ~/docker-compose
      #       mv ~/docker-compose /usr/local/bin/docker-compose
      #       ln -sf /usr/local/bin/docker-compose /usr/bin/docker-compose
      - setup_remote_docker
      - run: |
          ./.circleci/pull_image nsm-crm7-claim

      # Add other images (i.e. assess, appstore and claim) to pull
      - run:
          name: Build / Check services are up
          command: |
            cd /home/circleci/project
            docker-compose build
            docker-compose run start_applications

      - run:
          name: Run end to end tests
          command: |
            cd /home/circleci/project
            docker-compose run --name nsm-e2e-tests nsm-e2e-tests

workflows:
  build:
    jobs:
      - run-e2e-tests:
          context: nsm-e2e-test-production
