#!/bin/bash
DOCKER_COMPOSE_SERVICE_NAME=$1
cd /home/circleci/project
echo "Pulling image for $DOCKER_COMPOSE_SERVICE_NAME"
echo "Logging into ECR"
aws ecr get-login-password --region "eu-west-2" | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.eu-west-2.amazonaws.com
docker-compose pull $DOCKER_COMPOSE_SERVICE_NAME
