#!/bin/bash
DOCKER_COMPOSE_SERVICE_NAME=$1
cd /home/circleci/project
aws ecr get-login-password --region $ECR_REGION | docker login --username AWS --password-stdin ${AWS_ECR_REGISTRY_ID}.dkr.ecr.${ECR_REGION}.amazonaws.com
cd /usr/local/bin/docker-compose
ls
docker-compose pull $DOCKER_COMPOSE_SERVICE_NAME
