name: 'Run E2E Tests'
description: 'Run end-to-end tests for the LAA crime forms services'

runs:
  using: "composite"
  steps:
    - name: Checkout E2E Test Repository
      uses: actions/checkout@v3
      with:
        repository: ministryofjustice/nsm-e2e-test
        path: e2e-tests
    - name: Extract base registry URL and set repository URLs
      run: |
        # Extract the base registry URL (everything before the last '/')
        BASE_URL=$(echo $ECR_REGISTRY_URL | rev | cut -d/ -f2- | rev)

        echo "SUBMIT_IMAGE_URL=${BASE_URL}/${SUBMIT_DEV_ECR_REPOSITORY}:latest" >> $GITHUB_ENV
        echo "ASSESS_IMAGE_URL=${BASE_URL}/${ASSESS_DEV_ECR_REPOSITORY}:latest" >> $GITHUB_ENV
        echo "APPSTORE_IMAGE_URL=${BASE_URL}/${APP_STORE_DEV_ECR_REPOSITORY}:latest" >> $GITHUB_ENV

    # laa-submit-crime-forms
    - name: Configure AWS credentials for laa-submit-crime-forms
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.SUBMIT_DEV_ECR_ROLE_TO_ASSUME }}
        aws-region: ${{ secrets.SUBMIT_DEV_ECR_REGION }}
        role-session-name: ${{ secrets.ECR_ROLE_SESSION_NAME }}

    - name: Pull laa-submit-crime-forms image
      working-directory: e2e-tests
      run: |
        docker pull $ASSESS_IMAGE_URL

    # laa-crime-application-store
    - name: Configure AWS credentials for AppStore
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.APP_STORE_DEV_ECR_ROLE_TO_ASSUME }}
        aws-region: ${{ env.APP_STORE_ECR_REGION }}
        role-session-name: ${{ secrets.ECR_ROLE_SESSION_NAME }}

    - name: Login to ECR for AppStore
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: Pull NSCC appstore image
      shell: bash
      working-directory: e2e-tests
      run: |
        docker pull $APPSTORE_IMAGE_URL

    # laa-assess-crime-forms
    - name: Configure AWS credentials for Caseworker
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ env.ASSESS_DEV_ECR_ROLE_TO_ASSUME }}
        aws-region: ${{ env.ASSESS_DEV_ECR_REGION }}
        role-session-name: ${{ secrets.ECR_ROLE_SESSION_NAME }}

    - name: Login to ECR for Caseworker
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: 'true'

    - name: Pull NSCC caseworker image
      working-directory: e2e-tests
      run: |
        docker pull $ASSESS_IMAGE_URL

    - name: Build and check/wait for services
      working-directory: e2e-tests
      run: |
        docker-compose build
        docker-compose run start_applications

    - name: Run end-to-end tests
      working-directory: e2e-tests
      run: |
        docker-compose run laa-crime-forms-end-to-end-tests

    - name: Output container logs on failure
      if: failure()
      working-directory: e2e-tests
      run: |
        docker-compose logs

    - name: Cleanup
      if: always()
      working-directory: e2e-tests
      run: docker-compose down -v
