name: End-to-End Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-e2e-tests:
    name: Call E2E Tests
    uses: ministryofjustice/nsm-e2e-test/.github/workflows/run-e2e-tests.yml@7d1fa16be0d29c05461cbedf4e94a863d5c68fbc
    secrets: inherit
    permissions:
      id-token: write
      contents: read
