name: End-to-End Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-e2e-tests:
    name: Call E2E Tests
    uses: ministryofjustice/nsm-e2e-test/.github/workflows/run-e2e-tests.yml@3d1c7a09383986b97a9474756315bbbfcd4124dd
    secrets: inherit
    permissions:
      id-token: write
      contents: read
